[build]
  command = "npm run build" 
  publish = "./public" 
  functions = "./server" 

[build.environment]
  # Dominio del sitio de producción (Frontend)
	GATSBY_NFUNC_URL_PREFIX= 'http://localhost:9000'
	
	# Locations de las netlify functions (Backend) 
	# Son los mismos nombres de los archivos que hay en la carpeta /src/service
  
	GATSBY_URL_EMPLEADOS='/.netlify/functions/empleados'
	GATSBY_URL_FUNCIONES='/.netlify/functions/Funciones'
	GATSBY_URL_FIRMA='/.netlify/functions/GuardarImagen'
	GATSBY_URL_PHOTO='/.netlify/functions/GuardarPhoto'
	GATSBY_URL_EDITARFORMULA='/.netlify/functions/EditarFormula'
	GATSBY_URL_EDITARORDENP='/.netlify/functions/EditarOrdenP'
	GATSBY_URL_EDITARSECUENCIA='/.netlify/functions/EditarSecuencia'
	GATSBY_URL_FORMULA='/.netlify/functions/GetFormula'
	GATSBY_URL_FORMULAS='/.netlify/functions/GetFormulas'
	GATSBY_URL_MENUS='/.netlify/functions/GetMenus'
	GATSBY_URL_ORDENESP='/.netlify/functions/GetOrdenesP'
	GATSBY_URL_ORDENP='/.netlify/functions/GetOrdenP'
	GATSBY_URL_SECUENCIA='/.netlify/functions/GerSecuencia'
	GATSBY_URL_SECUENCIAS='/.netlify/functions/GerSecuencias'
	GATSBY_URL_GUARDARORDENP='/.netlify/functions/GuardarOrdenP'
	GATSBY_URL_GUARDARSECUENCIA='/.netlify/functions/GuardarSecuencia'
	GATSBY_URL_GUARDARFORMULA='/.netlify/functions/GuardarFormula'
	


	# Dominio del sitio de las APIs (Backend)
	GATSBY_ZAURU_PREFIX='https://app.zauru.com'
	GATSBY_URL_API = 'https://dcgse.com/calendario_api/apical'
	GATSBY_URL_APIP = 'https://dcgse.com/calendario_api/apiprod'
	GATSBY_URL_IMAGES = 'https://dcgse.com/calendario_api/uploads'

	# Locations de los enpoints GET de información a mostrar en los pasos de la app
	GATSBY_APIP_INDEX = ''
	GATSBY_APIP_ORDEN = '/orden'
	GATSBY_APIP_GUARDARORDEN = '/guardarorden'
	GATSBY_APIP_EDITARORDEN = '/editarorden'
	GATSBY_APIP_FORMULAS = '/formulas'
	GATSBY_APIP_FORMULA = '/formula'
	GATSBY_APIP_GUARDARFORMULA = '/guardarformula'
	GATSBY_APIP_EDITARFORMULA = '/editarformula'
	GATSBY_APIP_SECUENCIAS = '/secuencias'
	GATSBY_APIP_SECUENCIA = '/secuencia'
	GATSBY_APIP_GUARDARSECUENCIA = '/guardarsecuencia'
	GATSBY_APIP_EDITARSECUENCIA = '/editarsecuencia'
	GATSBY_APIP_GROUPMENU = '/groupmenu'

   

	# Email y token de autenticación para utilizar las APIs 
        GATSBY_EMAIL='api@cyclo.com.gt'
        GATSBY_TOKEN='Zs-HsGfE1xHQRtqPMRJ9'
		GATSBY_API_KEY='Zs-HsGfE1xHQRtqPMRJ9'
		#GATSBY_EMAIL='api@discogua.com.gt'
        #GATSBY_TOKEN='uuvDJ6vscs1ewsxbRVHU'
		#GATSBY_API_KEY='uuvDJ6vscs1ewsxbRVHU'
	# Variable de entorno para ver los botones de debug. 
	GATSBY_MODO='PROD' # PROD / DEBUG 
